name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        cc:
        - gcc
        - clang
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: check C compiler version
      run:
        ${{matrix.cc}} --version
    - name: build
      run:
        make CC=${{matrix.cc}}
    - name: APT install test deps
      run: |
        sudo apt-get install tmux
    - name: run tests
      run:
        perl -Mautodie=exec -e '$SIG{PIPE}="DEFAULT"; exec @ARGV'
        make test
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README
      if: matrix.os != 'ubuntu-18.04'

# vim:ts=2 sts=2 sw=2 et
